layout_spectrum: 0.1630824
typography_spectrum: 0.3189964
color:
  saturation: 0.6121156
  lightness: 0.9750103
  brandStrength: 0.7831327
  rhythmicContrast: 0.4929321
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: ASIATICA
